<?php
/**
 * CarteBlanche - PHP framework package - Installers package
 * Copyleft (c) 2013 Pierre Cassat and contributors
 * <www.ateliers-pierrot.fr> - <contact@ateliers-pierrot.fr>
 * License GPL-3.0 <http://www.opensource.org/licenses/gpl-3.0.html>
 * Sources <https://github.com/atelierspierrot/carte-blanche>
 */

namespace CarteBlancheInstaller;

use Composer\Composer,
    Composer\IO\IOInterface,
    Composer\Autoload\AutoloadGenerator,
    Composer\Package\PackageInterface,
    Composer\Repository\RepositoryInterface,
    Composer\Util\Filesystem,
    Composer\Script\EventDispatcher;

use AssetsManager\Config;

use CarteBlancheInstaller\CarteBlancheInstaller;

/**
 * The application bootstrap generator
 *
 * @author 		Piero Wbmstr <piero.wbmstr@gmail.com>
 */
class BootstrapGenerator extends AutoloadGenerator
{

    protected $composer;
    protected $config;

    public function __construct(Composer $composer, IOInterface $io)
    {
        $this->composer = $composer;
        $this->config = $composer->getConfig();
        parent::__construct($composer->getEventDispatcher());
    }

    public function generate(PackageInterface $mainPackage)
    {
        $filesystem = new Filesystem();
        $vendorDir = $this->config->get('vendor-dir');
        $vendorPath = strtr(realpath($vendorDir), '\\', '/');
        $appBasePath = str_replace($vendorDir, '', $vendorPath);
        $relVendorPath = $filesystem->findShortestPath(getcwd(), $vendorPath, true);

        $bootstrapFile = <<<EOF
<?php

// bootstrap.php generated by CarteBlanche

namespace App\Bootstrap;
use App\Bootstrap\SafeBootstrap;
class ContainerBootstrap extends SafeBootstrap {

    protected \$bundles = array(

EOF;

        $localRepo = $this->composer->getRepositoryManager()->getLocalRepository();
        $packageMap = $this->buildPackageMap($this->composer->getInstallationManager(), $mainPackage, $localRepo->getPackages());
        $autoloads = $this->parseAutoloads($packageMap, $mainPackage);

        foreach ($autoloads['psr-0'] as $namespace => $paths) {
            $exportedPaths = array();
            foreach ($paths as $path) {
                if (strstr($path, 'bundles'))
                {
                    $exportedPaths[] = var_export( trim( str_replace(Config::get('bundle-dir'), '', $path), '/'), 1);
                }
            }
            if (count($exportedPaths)>0) {
                $exportedPrefix = var_export($namespace, true);
                $bootstrapFile .= "        $exportedPrefix => ";
                if (count($exportedPaths) > 1) {
                    $bootstrapFile .= "array(".implode(', ', $exportedPaths)."),\n";
                } else {
                    $bootstrapFile .= $exportedPaths[0].",\n";
                }
            }
        }

        $bootstrapFile .= <<<EOF
    );
    
    protected \$prod_stacks = array(
        'database'          =>'initDatabase'
    );
    
    protected \$dev_stacks = array(
        'database'          =>'initDatabase',
        'unit_test'         =>'initUnitTest'
    );
    
}

EOF;

        return file_put_contents(
            rtrim($appBasePath, '/') . '/' . rtrim(Config::get('config-dir'), '/') . '/bootstrap.php',
            $bootstrapFile);
    }

}

// Endfile